name: Deploy Portfolio

on:
  push:
    branches:
      - main  # or "master" depending on your default branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./HACKATHONS  # ⬅️ this is correct for your repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
